all: moses-scripts subword-nmt sacreBLEU

moses-scripts:
	git clone https://github.com/amunmt/moses-scripts
subword-nmt:
	git clone https://github.com/rsennrich/subword-nmt
sacreBLEU:
	git clone https://github.com/mjpost/sacreBLEU
