all: moses-scripts subword-nmt sacreBLEU

moses-scripts:
	git clone https://github.com/marian-nmt/moses-scripts
subword-nmt:
	git clone https://github.com/rsennrich/subword-nmt
sacreBLEU:
	git clone https://github.com/marian-nmt/sacreBLEU -b master
